<?php

/**
 * @file
 * Install and update functions for the menu_views module.
 */

/**
 * Implements hook_install().
 */
function menu_views_install() {
  db_update('system')
    ->fields(array(
      'weight' => 100,
    ))
    ->condition('type', 'module')
    ->condition('name', 'menu_views')
    ->execute();
}

/**
 * Implements hook_update_last_removed().
 */
function menu_views_update_last_removed() {
  return 7200;
}

