<?php

/**
 * @file
 * Module to allow Views to be attached as menu items.
 *
 * This module is a utility module and allows an admin to select a view for a menu item instead of a title and link. When
 * the link is rendered, the view is inserted instead of the link. In addition, if the
 * parent item of the menu is a node page, the node id can be passed to the view as an argument using tokens.
 *
 * Original concept by Randall Knutson - LevelTen Interactive.
 * Written and maintained by Mark Carver - LevelTen Interactive.
 * http://www.leveltendesign.com
 */
 
// Include admin form alter hooks.
include_once('menu_views.admin.inc');

/**
 * Implements hook_menu().
 */
function menu_views_menu() {
  // Fake callback, needed for menu item add/edit validation.
  $items['<view>'] = array(
    'page callback' => 'drupal_not_found',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function menu_views_permission() {
  return array(
    'administer menu views' => array(
      'title' => t('Administer menu views'),
      'description' => t('Allows administrators to attach views to individual menu items and alter the view\'s configuration.'),
    ),
  );
}

/**
 * Implements hook_theme_registry_alter().
 * Intercepts theme_menu_link().
 */
function menu_views_theme_registry_alter(&$registry) {
  // Save previous value from registry in case another module/theme overwrites theme_menu_link() as well.
  $registry['menu_views_menu_link_default'] = $registry['menu_link'];
  $registry['menu_link']['function'] = 'menu_views_menu_link';
  // Provide Superfish support.
  if (isset($registry['superfish_menu_item_link'])) {
    $registry['menu_views_superfish_menu_item_link_default'] = $registry['superfish_menu_item_link'];
    $registry['superfish_menu_item_link']['function'] = 'menu_views_superfish_menu_item_link';
  }
}

/**
 * Implements theme_menu_link().
 * Overrides default theming function to intercept views.
 */
function menu_views_menu_link(array $variables) {
  // Only intercept if this menu link is a view.
  if (isset($variables['element']) && $view = _menu_views_replace_menu_item($variables['element'])) {
    $sub_menu = '';
    if ($variables['element']['#below']) {
      $sub_menu = drupal_render($variables['element']['#below']);
    }
    return '<li' . drupal_attributes($variables['element']['#attributes']) . '>' . $view . $sub_menu . "</li>\n";
  }
  // Otherwise, use the default theming function.
  return theme('menu_views_menu_link_default', $variables);
}

/**
 * Implements theme_superfish_menu_item_link().
 * Overrides default theming function to intercept views.
 */
function menu_views_superfish_menu_item_link(array $variables) {
  // Only intercept if this menu item link is a view.
  if (isset($variables['menu_item']['link']) && $view = _menu_views_replace_menu_item($variables['menu_item']['link'])) {
    return '<div class="menu-view">' . $view . '</div>';
  }
  // Otherwise, use the default theming function.
  return theme('menu_views_superfish_menu_item_link_default', $variables);
}

/**
 * Implements hook_menu_breadcrumb_alter().
 */
function menu_views_menu_breadcrumb_alter(&$active_trail, $item) {
  foreach ($active_trail as $key => $parent) {
    if ($parent['link_path'] == '<view>') {
      $menu_view = _menu_views_item($parent);
      _menu_views_tokenize($menu_view);
      // Remove this breadcrumb if the menu item view wants it hidden.
      if (!(bool)$menu_view['view']['settings']['breadcrumb']) {
        unset($active_trail[$key]);
      }
      else {
        // Use overriden title if provided.
        $title = $menu_view['view']['settings']['breadcrumb_title'];
        // Use title provided by view next.
        if (empty($title)) {
          $view = views_get_view($menu_view['view']['name']);
          if ($view && $view->access($menu_view['view']['display']) && $view->set_display($menu_view['view']['display'])) {
            $title = $view->get_title();
            $view->destroy();
          }
        }
        // If title is still empty, just remove it from the breadcrumb.
        if (empty($title)) {
          unset($active_trail[$key]);
        }
        else {
          $active_trail[$key]['title'] = $title;
          $active_trail[$key]['href'] = $menu_view['view']['settings']['breadcrumb_path'];
        }
      }
    }
  }
}

function _menu_views_replace_menu_item($element) {
  $output = FALSE;
  // Only process menu links that are not on admin pages (see: http://drupal.org/node/1790444).
  if (!path_is_admin(current_path())) {
    $item = _menu_views_item($element);
    _menu_views_tokenize($item);
    if ($item['type'] == 'view' && $item['view']['name'] && $item['view']['display']) {
      $element['#attributes']['class'][] = 'menu-views';
      if ($view = views_get_view($item['view']['name'])) {
        if ($view->access($item['view']['display']) && $view->set_display($item['view']['display'])) {
          $output = '';
          $view->set_arguments(explode('/', $item['view']['arguments']));
          // Provide title options for the view.
          if ((bool)$item['view']['settings']['title']) {
            $title = $item['view']['settings']['title_override'];
            if (empty($title)) {
              $title = $view->get_title();
            }
            if (!empty($title)) {
              $wrapper = $item['view']['settings']['title_wrapper'];
              if ($wrapper === '0') {
                $wrapper = FALSE;
              }
              elseif ($wrapper === '') {
                $wrapper = 'h3';
              }
              if ($wrapper) {
                $output .= '<' . $wrapper . (!empty($item['view']['settings']['title_classes']) ? ' class="' . $item['view']['settings']['title_classes'] . '"' : '') . '>';
              }
              $output .= $title;
              if ($wrapper) {
                $output .= '</' . $wrapper . '>';
              }
            }
          }
          $output .= $view->preview();
          $view->destroy();
        }
      }
    }
  }
  return $output;
}

function _menu_views_default_values() {
  return array(
    'mlid' => 0,
    'type' => 'link',
    'tree' => FALSE,
    'original_path' => '',
    'view' => array(
      'name' => FALSE,
      'display' => FALSE,
      'arguments' => '',
      'settings' => array(
        'breadcrumb' => TRUE,
        'breadcrumb_title' => '',
        'breadcrumb_path' => '<front>',
        'title' => FALSE,
        'title_wrapper' => '',
        'title_classes' => '',
        'title_override' => '',
      ),
    ),
  );
}

function _menu_views_item(&$element = array(), &$form_state = array()) {
  // Default values.
  $item = $default = _menu_views_default_values();
  $provided = FALSE;
  // Attempt to load the menu view element for a link.
  if (isset($element['menu_views'])) {
    $provided = &$element['menu_views'];
  }
  if (!$provided && isset($element['localized_options']['menu_views'])) {
    $provided = &$element['localized_options']['menu_views'];
  }
  if (!$provided && isset($element['#localized_options']['menu_views'])) {
    $provided = &$element['#localized_options']['menu_views'];
  }
  // If the menu view element were not set, attempt to determine if this is a form.
  if (!$provided && isset($element['options'])) {
    if (isset($element['options']['#tree']) && $element['options']['#tree']) {
      $item['tree'] = TRUE;
    }
    if (isset($element['original_item']['#value']['options']['menu_views'])) {
      $provided = &$element['original_item']['#value']['options']['menu_views'];
    }
    if ($item['tree'] && isset($form_state['values']['options']['menu_views'])) {
      $provided = &$form_state['values']['options']['menu_views'];
    }
    elseif (isset($form_state['values']['menu_views'])) {
      $provided = &$form_state['values']['menu_views'];
    }
    if (isset($form_state['values']['menu_item_type'])) {
      $item['type'] = $form_state['values']['menu_item_type'];
    }
  }
  // By default, the menu view returns default values (no view). If settings were provided by an element or form item, then use those.
  if ($provided) {
    // Extract available element settings to use for this menu view.
    foreach (array('mlid', 'type', 'original_path', 'view') as $property) {
      if (isset($provided[$property]) && !empty($provided[$property])) {
        if (is_array($item[$property])) {
          $item[$property] = _menu_views_array_merge_recursive($item[$property], $provided[$property]);
        }
        else {
          $item[$property] = $provided[$property];
        }
      }
    }
  }
  // Filter out any disabled views.
  $views = array_keys(views_get_enabled_views());
  if (!in_array($item['view']['name'], $views)) {
    $item['view'] = $default['view'];
  }
  return $item;
}

/**
 * Implements hook_token_info().
 */
function menu_views_token_info() {
  $tokens['tokens']['menu-link']['node'] = array(
    'name' => t('Node'),
    'description' => t('The node of the menu link.'),
    'type' => 'node',
  );
  $tokens['tokens']['menu-link']['parent']['node'] = array(
    'name' => t('Node'),
    'description' => t('The node of the menu link\'s parent.'),
    'type' => 'node',
  );
  return $tokens;
}

/**
 * Implements hook_tokens().
 */
function menu_views_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $url_options = array('absolute' => TRUE);
  if (isset($options['language'])) {
    $url_options['language'] = $options['language'];
    $language_code = $options['language']->language;
  }
  else {
    $language_code = NULL;
  }
  $sanitize = !empty($options['sanitize']);

  $replacements = array();
  $node = FALSE;
  $parent = FALSE;
  // Menu link tokens.
  if ($type == 'menu-link' && !empty($data['menu-link'])) {
    $link = (array) $data['menu-link'];
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'node':
          $node = menu_get_object('node', 1, $link['link_path']);
          if ($node && $node->nid) {
            $title = $node->title;
            $replacements[$original] = $sanitize ? filter_xss($title) : $title;
          }
          else {
            $replacements[$original] = NULL;
          }
          break;
        case 'parent':
          if (isset($link['plid']) &&
            !empty($link['plid']) &&
            ($parent = menu_link_load($link['plid'])) &&
            ($node = menu_get_object('node', 1, $parent['link_path'])) &&
            $node->nid
          ) {
            $title = $node->title;
            $replacements[$original] = $sanitize ? filter_xss($title) : $title;
          }
          else {
            $replacements[$original] = NULL;
          }
          break;
      }
    }
    // Chained token relationships.
    if (($node_tokens = token_find_with_prefix($tokens, 'node')) &&
      $node = menu_get_object('node', 1, $link['link_path'])
    ) {
      $replacements += token_generate('node', $node_tokens, array('node' => $node), $options);
    }
    if (($parent_tokens = token_find_with_prefix($tokens, 'parent')) &&
      isset($link['plid']) &&
      !empty($link['plid']) &&
      ($parent = menu_link_load($link['plid'])) &&
      ($node = menu_get_object('node', 1, $parent['link_path'])) &&
      $node->nid
    ) {
      $replacements += token_generate('node', $parent_tokens, array('node' => $node), $options);
    }
  }
  return $replacements;
}

/**
 * Helper function to tokenize a menu item view arguments and settings.
 * Alters the menu view item array and the original values are replaced.
 */
function _menu_views_tokenize(&$item, $human_readable = FALSE) {
  if (isset($item['mlid']) && $item['mlid'] > 0) {
    $context['menu-link'] = menu_link_load($item['mlid']);
    $options = array(
      'callback' => '_menu_views_tokenize_callback',
      'human_readable' => $human_readable,
    );
    if (isset($item['view']['arguments']) && !empty($item['view']['arguments'])) {
      $item['view']['arguments'] = token_replace($item['view']['arguments'], $context, array_merge($options, array('urlencode' => TRUE, 'clear' => TRUE)));
    }
    $tokenizable_settings = array('breadcrumb_title', 'breadcrumb_path', 'title_override');
    if (isset($item['view']['settings'])) {
      foreach ($item['view']['settings'] as $key => $value) {
        if (in_array($key, $tokenizable_settings)) {
          $item['view']['settings'][$key] = token_replace($value, $context, $options);
        }
      }
    }
  }
}

/**
 * Callback for human-readable token value replacements.
 */
function _menu_views_tokenize_callback(&$replacements, $data, $options) {
  foreach ($replacements as $token => $value) {
    if (isset($options['urlencode']) && $options['urlencode']) {
      $replacements[$token] = urlencode($value);
    }
    if (isset($options['human_readable']) && $options['human_readable']) {
      if (is_bool($value)) {
        $value = $value ? t('TRUE') : t('FALSE');
      }
      elseif (is_object($value)) {
        $value = t('Object');
      }
      elseif (is_array($value)) {
        $value = t('Array');
      }
      elseif (is_null($value)) {
        $value = t('NULL');
      }
      else {
        $value = (string) $value;
      }
      if ($value === '') {
        $value = t('NULL');
      }
    }
  }
}

/**
 * array_merge_recursive does indeed merge arrays, but it converts values with duplicate
 * keys to arrays rather than overwriting the value in the first array with the duplicate
 * value in the second array, as array_merge does. I.e., with array_merge_recursive,
 * this happens (documented behavior):
 * 
 * array_merge_recursive(array('key' => 'org value'), array('key' => 'new value'));
 *     => array('key' => array('org value', 'new value'));
 * 
 * array_merge_recursive_distinct does not change the datatypes of the values in the arrays.
 * Matching keys' values in the second array overwrite those in the first array, as is the
 * case with array_merge, i.e.:
 * 
 * array_merge_recursive_distinct(array('key' => 'org value'), array('key' => 'new value'));
 *     => array('key' => 'new value');
 * 
 * Parameters are passed by reference, though only for performance reasons. They're not
 * altered by this function.
 * 
 * @param array $array1
 * @param mixed $array2
 * @author daniel@danielsmedegaardbuus.dk
 * @return array
 */
function &_menu_views_array_merge_recursive(array &$array1, &$array2 = null)
{
  $merged = $array1;
 
  if (is_array($array2))
    foreach ($array2 as $key => $val)
      if (is_array($array2[$key]))
        $merged[$key] = is_array($merged[$key]) ? _menu_views_array_merge_recursive($merged[$key], $array2[$key]) : $array2[$key];
      else
        $merged[$key] = $val;
 
  return $merged;
}